Feat/simple white label form
kocsislaci/kotlin_sdk pull request #1
Opened 2022-09-12 16:03 UTC by thunderTheGun

2022-09-13 22:00 UTC, Roverr requested changes
Overall looks good for me, I have some formatting change requests

2022-09-13 22:00 UTC, Roverr commented on build.gradle
> +           google()
Unnecessary space

2022-09-13 22:00 UTC, Roverr commented on sample/build.gradle
> +    implementation("io.coil-kt:coil-compose:2.2.0")
Let's make these lines consistent, it should be `"implementation 'io.coil-kt:coil-compose:2.2.0"`

Use double quotes, don't use brackets

@kocsislaci also fair that the original one is inconsistant as well, sometimes it is double quotes sometimes it is single quotes. Not sure if this should be the scope of this PR

2022-09-13 22:00 UTC, Roverr commented on sample/src/main/java/com/github/paylike/sample/view/WhiteLabelFormView.kt
> +                            {
Weird formatting. Is this spotless?

Does spotless support this syntax @kocsislaci  ?

2022-09-13 22:00 UTC, Roverr commented on sample/src/main/java/com/github/paylike/sample/viewmodel/WhiteLabelActivity.kt
> +    }
Either keep spaces between functions or don't, but consistancy!

2022-09-14 08:37 UTC, kocsislaci requested changes

2022-09-14 08:37 UTC, kocsislaci commented on sample/build.gradle
> +    implementation("io.coil-kt:coil-compose:2.2.0")
In groovy (and I guess in many other languages) you have to use double quotes if you want to use string interpolation. In the other libraries, only those literals have double quotes where we included string interpolation.

Other than that, I support if we make everywhere consistent. The next iteration of refactor and improvements can include this consistency check.

2022-09-14 08:37 UTC, kocsislaci commented on sample/src/main/java/com/github/paylike/sample/ui/theme/Color.kt
>  val Purple200 = Color(0xFFBB86FC)
Do we need these other colour definitions? If we only use the Paylike style, we can delete them, can't we? :)

2022-09-14 08:37 UTC, kocsislaci commented on sample/src/main/java/com/github/paylike/sample/view/WhiteLabelFormView.kt
> +                            {
Spotless is not yet configured in this repo. But I started configuring it in the feature/initial-release branch.
Spotless support Google and KotlinLang style; if we run spotless, it will probably decide if it's good or not.
Other repos use kotlinLang.

2022-09-14 08:37 UTC, kocsislaci commented on sample/src/main/java/com/github/paylike/sample/view/WhiteLabelFormView.kt
> +@SuppressLint("UnusedMaterialScaffoldPaddingParameter")
We can get rid of this @SuppressLint if we add a param for the lambda "content = {...}". See my other comment some rows lower

2022-09-14 08:37 UTC, kocsislaci commented on sample/src/main/java/com/github/paylike/sample/view/WhiteLabelFormView.kt
> +                content = {
Here: 
" content = { padding -> "
then we can use this param to set the inner composable's padding.
E. g.
"Column(
    modifier = Modifier.padding(padding),
) { "
https://stackoverflow.com/questions/70209466/what-is-the-purpose-of-the-paddingvalues-parameter-in-a-scaffold
I see that the padding is set to zero; if by any chance we change the scaffold bottom bar, then this could be a problem.

Well, now it's not necessary :D but I prefer not to use these linter suppressions, what do you think?

2022-09-14 08:37 UTC, kocsislaci commented on sample/src/main/java/com/github/paylike/sample/view/WhiteLabelFormView.kt
> +                content = {
Other rather just styling question :D If we delegated the composable functionalities to distinct functions, then we can make it with the "content" as well. Then the code base nicely separates the scaffold skeleton, and we can see later the functions it calls.

2022-09-14 08:37 UTC, kocsislaci commented on sample/src/main/java/com/github/paylike/sample/view/WhiteLabelFormView.kt
> +                            {
As I'm thinking about it, I'm getting sure spotless is going to solve every issue of this kind.

2022-09-14 08:37 UTC, kocsislaci commented on sample/src/main/java/com/github/paylike/sample/view/WhiteLabelFormView.kt
> +private fun TopBarContent() {
Why are some functions private and others not?

2022-09-14 08:37 UTC, kocsislaci commented on sample/src/main/res/drawable/ic_mastercard_icon.xml
> +</vector>
No newline at end of the file. Do we need that here?

2022-09-14 08:37 UTC, kocsislaci commented on sample/src/main/java/com/github/paylike/sample/view/WhiteLabelFormView.kt
> +        super.onCreate(savedInstanceState)
I would encourage the viewModel instantiation in the scope of Activity -> onCreate() and not in the scope of composable.
e. g. "val viewModel: WhiteLabelViewModel by viewModels()"
then
we can add this as a parameter to the composable.

I don't think it's crucial in this sample application, but It's an overall recommendation and practice of the android framework.
https://developer.android.com/topic/libraries/architecture/viewmodel here; it says the same in the activity example code.

2022-09-14 08:37 UTC, kocsislaci commented on sample/src/main/java/com/github/paylike/sample/viewmodel/WhiteLabelActivity.kt
> +            uiState = uiState.copy(cardNumber = newValue)
In this case, the .copy(...) function is not the best choice.
"If you want to retain the original object and return an immutable copy of it, you can use the function [copy()](https://kotlinlang.org/docs/reference/data-classes.html#copying), provided in all instances of data classes."
So, we could use .apply(...) instead. It won't instantiate another object only sets the properties of the original, and as I see it, it is the intended practice here :)

2022-09-14 08:37 UTC, kocsislaci commented on sample/src/main/java/com/github/paylike/sample/viewmodel/WhiteLabelActivity.kt
> +            uiState = uiState.copy(cardNumber = newValue)
I checked it, and the data class consists only vars, so no problem using apply() instead and its less memory impact on the application

2022-09-14 08:37 UTC, kocsislaci commented on sample/src/main/java/com/github/paylike/sample/viewmodel/WhiteLabelActivity.kt
> +            uiState = uiState.copy(cardNumber = newValue)
Same applies for the other setter functions

2022-09-14 08:42 UTC, kocsislaci commented on sample/src/main/java/com/github/paylike/sample/viewmodel/WhiteLabelActivity.kt
> +            uiState = uiState.copy(cardNumber = newValue)
https://preslav.me/2016/06/26/kotlin-basics-apply-and-copy/
Here is the source of the difference between copy and apply

2022-09-14 10:11 UTC, thunderTheGun commented on sample/build.gradle
> +    implementation("io.coil-kt:coil-compose:2.2.0")
in the fix I use single everywhere except for inpterpolation

2022-09-14 10:13 UTC, thunderTheGun commented on sample/src/main/java/com/github/paylike/sample/view/WhiteLabelFormView.kt
> +                            {
@Roverr it's not spotless, it's pure thunderTheGun 😄

2022-09-14 10:23 UTC, thunderTheGun commented on sample/src/main/java/com/github/paylike/sample/ui/theme/Color.kt
>  val Purple200 = Color(0xFFBB86FC)
also, even the ones we use I did not call (just used Color.White for example)

2022-09-14 10:29 UTC, thunderTheGun commented on sample/src/main/java/com/github/paylike/sample/view/WhiteLabelFormView.kt
> +                content = {
I'd say it's more elegant not to do so :)

2022-09-14 10:39 UTC, thunderTheGun commented on sample/src/main/java/com/github/paylike/sample/view/WhiteLabelFormView.kt
> +                content = {
I see 'content' here as the main 'thing' that is going on in this class. It can be put to a separate function, but to me it does not add to the code. TopBarContent is different, it doesn't have a main role here, so having more code would kind of obstruct the point here. If the same thing happened to 'content', the reader would have to scroll more to get the meaning of the code.

This is only my viewpoint though, and I am open to discussion :) What advantages of refactoring 'content' to a composable did I miss?

2022-09-14 10:41 UTC, thunderTheGun commented on sample/src/main/java/com/github/paylike/sample/view/WhiteLabelFormView.kt
> +private fun TopBarContent() {
no real reason

2022-09-14 10:42 UTC, thunderTheGun commented on sample/src/main/res/drawable/ic_mastercard_icon.xml
> +</vector>
I guess it doesn't hurt :)

2022-09-14 12:13 UTC, Roverr commented on sample/src/main/java/com/github/paylike/sample/viewmodel/WhiteLabelActivity.kt
> +            uiState = uiState.copy(cardNumber = newValue)
Are you sure about this? It is a fairly common practice to make your state objects immutable, therefore tracking changes becomes easier. A great example is how React maintains hook states.
```
const MyComponent = () => {
  const [myState, setMyState] = useState({ foo: 'bar' })
}
```

When `setMyState` is called, you are passing a new object and overwriting the original one. The reason for this is that the object that you use can be nested to hell which increases the complexity of change tracking. 

Now I am fairly sure that this is also the case with Kotlin's `mutableStateOf`. While you are using atomic types, changes can be tracked as nesting is impossible. However, when you use a data class, it is not guaranteed that it wont contain another data class that contains another data class etc... Hence the reason why I believe that mutating your state object will not result in a rerender in this setup.

2022-09-14 12:16 UTC, kocsislaci commented on sample/src/main/java/com/github/paylike/sample/viewmodel/WhiteLabelActivity.kt
> +            uiState = uiState.copy(cardNumber = newValue)
Makes sense. But in this case, the data class can contain only val-s not var-s.

2022-09-14 12:17 UTC, kocsislaci commented on sample/src/main/java/com/github/paylike/sample/viewmodel/WhiteLabelActivity.kt
> +            uiState = uiState.copy(cardNumber = newValue)
MAKE VAL NOT (W)VAR

2022-09-14 12:40 UTC, thunderTheGun commented on sample/src/main/java/com/github/paylike/sample/viewmodel/WhiteLabelActivity.kt
> +            uiState = uiState.copy(cardNumber = newValue)
I like the theory behind, just like with other methods I tried before. The sad thing is, neither of them worked, and the same is true for .apply(). 

I think keeping the same object does not trigger a recomposition. You have to keep making new objects -> when the compose object (form) detects a new object is given as state, it notices the change and rerenders itself. When a prop in the state changes, it may think "all fine, but the state object is the same", and does not refresh.

2022-09-22 09:37 UTC, Roverr approved these changes

2022-09-22 09:38 UTC, merged

2022-09-22 12:49 UTC, kocsislaci reviewed
Looks all good