Initial release
kocsislaci/kotlin_sdk pull request #2
Opened 2022-09-21 07:12 UTC by kocsislaci

2022-10-11 07:21 UTC, Roverr reviewed
Overall it is in an early stage, I have couple of suggestions.

Rather than the current directory structure, we should go with something like:

```
- whitelabel
  - simple
     - .... source
  - extendable
    - .... source
- paylike
  - ... source
```

And the other challenge that we need to think about is how can we make the extendable white label component truly extendable. Extending the viewmodel is fairly straight forward, but we need to enable our users to do the same with the view component.

2022-10-11 07:21 UTC, Roverr commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/simplewhitelabel/view/WhiteLabelForm.kt
> +    if (uiState.isSuccess) {
Seems unnecessary  to have two clauses?

2022-10-11 07:21 UTC, Roverr commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/simplewhitelabel/viewmodel/WhiteLabelViewModel.kt
> +                else if (cardNumberInput[0].digitToIntOrNull() == 5) CardBrands.MASTERCARD
2 and 6 are also Master card related

2022-10-11 07:21 UTC, Roverr commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/simplewhitelabel/view/WhiteLabelForm.kt
> +        Toast.makeText(LocalContext.current, "The transactionId is: ${viewModel.engine.repository.transactionId}", Toast.LENGTH_LONG).show()
We won't need this toast in the final version

2022-10-11 07:21 UTC, Roverr commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/simplewhitelabel/view/WhiteLabelForm.kt
> +        LaunchedEffect(scaffoldState.snackbarHostState) {
We won't need this in the final version. With the simple white label solution the user (developer) should decide what happens when the transaction is done. With the paylike style, we will show an animation.

2022-10-11 08:15 UTC, kocsislaci commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/simplewhitelabel/view/WhiteLabelForm.kt
> +    if (uiState.isSuccess) {
Exactly, these two popup messages are for test purposes. I included both because I wasn't sure if the toast would work the first time, then I left it like this to show it works :D

2022-10-11 08:16 UTC, kocsislaci commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/simplewhitelabel/viewmodel/WhiteLabelViewModel.kt
> +                else if (cardNumberInput[0].digitToIntOrNull() == 5) CardBrands.MASTERCARD
Okay, I haven't checked the validity of this information, but I am now.

2022-10-11 08:17 UTC, kocsislaci commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/simplewhitelabel/view/WhiteLabelForm.kt
> +        Toast.makeText(LocalContext.current, "The transactionId is: ${viewModel.engine.repository.transactionId}", Toast.LENGTH_LONG).show()
Noted, till the end it helps me debug if necessary :)

2022-10-11 08:17 UTC, kocsislaci commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/simplewhitelabel/view/WhiteLabelForm.kt
> +        LaunchedEffect(scaffoldState.snackbarHostState) {
👍

2022-10-12 12:12 UTC, kocsislaci commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/simplewhitelabel/viewmodel/WhiteLabelViewModel.kt
> +                else if (cardNumberInput[0].digitToIntOrNull() == 5) CardBrands.MASTERCARD
https://www.bindb.com/card-schemes

I found this. I add this to the implementation, taking into account that paylike supports visa, mastercard (including maestro).

2022-10-20 07:44 UTC, Roverr reviewed
Looks much more promising! I like the structure, and I like the extendable solution. Of course we need to clean it up, but overall it starts to take a shape. Good job 🌮

2022-10-20 07:44 UTC, Roverr commented on sample/src/main/java/com/github/paylike/sample/viewmodel/SampleViewModel.kt
> +                                                engine.addPaymentAdditionalData(extenderFields[0])
It would be nice to handle this inside our component automatically

2022-10-20 07:44 UTC, Roverr commented on sample/src/main/java/com/github/paylike/sample/viewmodel/SampleViewModel.kt
> +                                                expiryYear + 2000,
It might makes sense to handle this logic in the function. `If expiryYear < 2000 expiryYear+=2000`

2022-10-20 07:44 UTC, Roverr commented on sample/src/main/java/com/github/paylike/sample/viewmodel/SampleViewModel.kt
> +    val sdkExampleModelMap: Map<String, SdkExampleModel> =
We might need to separate this into multiple files to make it easier for developers to understand the example code

2022-10-20 07:44 UTC, Roverr commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/cardprovider/CalculateProviderFromNumber.kt
> +fun calculateProviderFromNumber(number: String): SupportedCardProviders {
Where are these regexes coming from?

2022-10-20 07:44 UTC, Roverr commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/whitelabel/simple/view/WhiteLabelComposable.kt
> +            MaterialTheme { content.invoke() }
It gets a default MaterialTheme right? I am interested what happens when the bootstrapping does not happen using Material. Something to take a look at before release.

2022-10-20 07:44 UTC, Roverr commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/whitelabel/extendable/viewmodel/ExtendableWhiteLabelViewModel.kt
> +    override fun update(o: Observable?, arg: Any?) {
I don't think we gonna need this overwrite

2022-10-20 09:10 UTC, kocsislaci commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/cardprovider/CalculateProviderFromNumber.kt
> +fun calculateProviderFromNumber(number: String): SupportedCardProviders {
https://www.bindb.com/card-schemes

2022-10-20 09:12 UTC, kocsislaci commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/whitelabel/extendable/viewmodel/ExtendableWhiteLabelViewModel.kt
> +    override fun update(o: Observable?, arg: Any?) {
aye aye

2022-10-20 12:27 UTC, kocsislaci commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/whitelabel/simple/view/WhiteLabelComposable.kt
> +            MaterialTheme { content.invoke() }
Yes, the default is MaterialTheme. You are right. It would be wiser to check for the actual theme used in this scope and set that for default.

2022-10-20 13:43 UTC, kocsislaci commented on sample/src/main/java/com/github/paylike/sample/viewmodel/SampleViewModel.kt
> +                                                engine.addPaymentAdditionalData(extenderFields[0])
It now has a default implementation inside the VM. Optionally we can overwrite it.

2022-11-28 08:48 UTC, Roverr requested changes
Well done, only a couple of small kinks to work out. 

Codewise:
* Noted on the PR
* We should experiment with adding this to an application that is above the supported API level, but does not use composable, how would that look like?

In the sample application (UI issues):
* We need to support rotation of the phone
* Let's use the paylike colours in the menu
* We need to make those menu items a bit more nicer, currently they are a bit ugly 😄 
* We need a back button in the scenarios, so users can quickly navigate back to the menu
* I think in the simple white label example we need some kind of feedback to show that the transaction ended successfully. For example we could write out "Your success message goes here" or something
* What do you think about allowing the user to scroll inside the forms? It should make the UX a bit more friendlier overall

2022-11-28 08:48 UTC, Roverr commented on README.md
> +### Used Android API level and Technologies
Used Android API level sounds a bit weird here, maybe we could just call it `Android API & underlying technology`

2022-11-28 08:48 UTC, Roverr commented on README.md
> +For the UI related design and implementation the chosen technology is **Jetpack Compose**.
We can link compose here I think https://developer.android.com/jetpack/compose

2022-11-28 08:48 UTC, Roverr commented on README.md
> +            test = PaymentTestDto(), // For test purposes
Is the PaymentData currently populated with the paymenttestDTO if it is missing but the apiMode is test?

2022-11-28 08:48 UTC, Roverr commented on README.md
> +This form provides the simplest implementation of a payment flow.
A new line before **Features** would make it easier to read

2022-11-28 08:48 UTC, Roverr commented on README.md
> +Every field has a realtime sanitation and check if its acceptable. Pushing the pay button has a check if every field meets the requirements, if not refuses to trigger the payment flow. If every field
>Pushing the pay button has a check if every field meets the requirements, if not refuses to trigger the payment flow.

Would be better this way:

Pushing the pay button starts a general validation process to ensure every field is filled according to its ruleset. If the validation fails, the payment flow does not start.

2022-11-28 08:48 UTC, Roverr commented on README.md
> +SampleActivity.kt
Before the example code we could provide a minimalistic gif to showcase the happy path. WDYT?

2022-11-28 08:48 UTC, Roverr commented on README.md
> +### Custom Theming
Here it would be also nice to see an example probably after the example usage.

Like we could have a small theme and say `for example our simple white label form look like this with this example theme`. Maybe not necessary, just thinking about how could we make this more easy to perceive for first glance

2022-11-28 08:48 UTC, Roverr commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/ErrorStatusCodeMap.kt
> +        //    ApiCodes.VERSION_MISSING to R.string.,
What are these comments?

2022-11-28 08:48 UTC, Roverr commented on README.md
> +# Paylike's Android SDK
I think it would be nice to have a developer documentation as well explaining how the res_generator part works

We don't have to put it into the main readme, we can create `./docs/DEVELOPMENT.md` or something. Anything else that is development related should also go there.

2022-11-28 08:48 UTC, Roverr commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/FieldComposables.kt
> +fun CardNumberField(
I don't like this file. The only thing common in these components is that they are composable and input fields. 

Why are these not implemented in the `whitelabel` directory? They are atomic parts of the view. 

Why do we have the note field input in the same file as the card number, expiry, cvc? The latter free are essential, you cannot not use them if you are using our high level components, however, you can avoid using the note as it should be optional. 

I'd suggest to go into one of these directions:
* Move this file into the `whitelabel` directory, so we can say that yeah, we only have 4 supported types of input fields, they are all related to the whitelabel implementation, makes no sense to separate
* Create a new directory for the atomic parts and separate our components into multiple files as in the context of being atomic and composable, they have nothing else in common

2022-11-28 08:48 UTC, Roverr commented on kotlin_sdk/src/main/java/com/github/paylike/kotlin_sdk/cardprovider/CalculateProviderFromNumber.kt
> +package com.github.paylike.kotlin_sdk.cardprovider
Now this on the other hand could be a single file in my opinion. All of them are just a single function / enum while they are also depending heavily on each other. Would make sense for me to move them into a single file

2022-12-09 12:14 UTC, Roverr approved these changes

2022-12-09 12:35 UTC, Roverr requested changes
On API 33 we still cannot scroll with iFrame

2023-01-25 09:59 UTC, merged